---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-inspector
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      application: mcp-inspector
  template:
    metadata:
      labels:
        application: mcp-inspector
    spec:
      serviceAccountName: default-editor
      containers:
        - name: mcp-inspector
          image: {{ .Values.mcpInspector.repository }}:{{ .Values.mcpInspector.tag }}
          imagePullPolicy: Always
          command: ["node", "client/bin/start.js", "--config", "/config/config.json", "--server", "everything"]
          ports:
          - containerPort: 6274
            protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: MCP_AUTO_OPEN_ENABLED
              value: "false"
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: mcp-inspector-config


# docker run --rm \
#  -p 127.0.0.1:6274:6274 \
#  -p 127.0.0.1:6277:6277 \
#  -e HOST=0.0.0.0 \
#  -e MCP_AUTO_OPEN_ENABLED=false \
#  ghcr.io/modelcontextprotocol/inspector:latest