apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mcp-inspector-vs
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
  - teknoir/teknoir-gateway
  hosts:
  - '{{- printf "mcp-inspector-%s.%s" .Release.Namespace .Values.domain -}}'
  http:
    - match:
      - uri:
          prefix: /mcp
      route:
      - destination:
          host: mcp-alerts.{{ .Release.Namespace }}.svc.cluster.local
          port:
            number: 80
    - match:
        - uri:
            prefix:
              /
      route:
        - destination:
            host: mcp-inspector.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
