---
apiVersion: v1
kind: Service
metadata:
  name: mcp-inspector
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    application: mcp-inspector
  ports:
    - port: 80
      targetPort: 6274
      protocol: TCP
      name: http-mcp-inspector
