# For backward compatibility
# Proxy and http://mcp-alerts/mcp should be used instead to connect to MCP Alerts server
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mcp-alerts-vs
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
  - teknoir/teknoir-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /{{ .Release.Namespace }}/mcp-alerts/
    rewrite:
      uri: /
    route:
    - destination:
        host: mcp-alerts.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80
